# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GameData',
        ),
    ]
